### PR TITLE
Separates collision with obstacle and collision with vehicle

### PR DESCRIPTION
**Pull request by mhtb32**
For some applications(like what I have in mind), it may be useful to separate vehicle to vehicle collision and vehicle to obstacle collision.

Please let me know if you think there is something wrong with these changes.

### CODE REVIEW

**Comment by mhtb32** [comment]
I have no clue why one of the checks failed :sweat_smile:

**Comment by eleurent** [comment]
Out of curiosity, what use-case do you have in mind where this distinction is needed?

No idea either why the docs failed but it's probably fine.

**Comment by mhtb32** [comment]
> Out of curiosity, what use-case do you have in mind where this distinction is needed?

I am using `Obstacle` as goal areas in a Multi-Goal environment and need to use `check_collision()` with instances of it. Also, I have other vehicles in the environment. So I wanted to know whether I've reached a goal or hit a vehicle.

Maybe better for future work to have an abstract class called `RoadObjects`,  which classes like `Obstacle` or `Landmark`(used for goals) inherit. What's your opinion?

**Comment by mhtb32** [comment]
And I have a question by the way, which I couldn't find the answer by surfing the code thoroughly.

I am developing an environment. For now, the `_is_terminal()` function always returns `False`, but even then, if `COLLISION_ENABLED` is `True`, in the rendering window vehicle gets blocked by obstacle and doesn't pass through it(like when `COLLISION_ENABLED` is `False`).

Where in the code such behavior is enforced?

**Comment by eleurent** [comment]
> 
> 
> > Out of curiosity, what use-case do you have in mind where this distinction is needed?
> 
> I am using `Obstacle` as goal areas in a Multi-Goal environment and need to use `check_collision()` with instances of it. Also, I have other vehicles in the environment. So I wanted to know whether I've reached a goal or hit a vehicle.
> 
> Maybe better for future work to have an abstract class called `RoadObjects`, which classes like `Obstacle` or `Landmark`(used for goals) inherit from. What's your opinion?

Totally agree, reaching a goal should probably not be implemented as colliding with an obstacle as it is now ^^ I agree that a common interface is needed.

**Comment by eleurent** [comment]
> 
> 
> And I have a question by the way, which I couldn't find the answer by surfing the code thoroughly.
> 
> I am developing an environment. For now, the `_is_terminal()` function always returns `False`, but even then, if `COLLISION_ENABLED` is `True`, in the rendering window vehicle gets blocked by obstacle and doesn't pass through it(like when `COLLISION_ENABLED` is `False`).
> 
> Where in the code such behavior is enforced?

I am not sure what you mean. If collisions are enabled, going through an obstacle results in `vehicle.crashed` being set to `True`, and further motion is prevented (regardless of whether it is considered a terminal state). So it is expected behaviour, isn't it?

**Comment by mhtb32** [comment]
> I am not sure what you mean. If collisions are enabled, going through an obstacle results in `vehicle.crashed` being set to `True`, and further motion is prevented (regardless of whether it is considered a terminal state). So it is expected behaviour, isn't it?

That's totally expected and right.
I just meant wherein the code further motion is prevented. I couldn't find that.

**Comment by mhtb32** [comment]
> Totally agree, reaching a goal should probably not be implemented as colliding with an obstacle as it is now ^^ I agree that a common interface is needed.

I make a separate issue about this to discuss the ideas and expectations, and eventually, decide the assignee.

**Comment by eleurent** [comment]
> 
> 
> > I am not sure what you mean. If collisions are enabled, going through an obstacle results in `vehicle.crashed` being set to `True`, and further motion is prevented (regardless of whether it is considered a terminal state). So it is expected behaviour, isn't it?
> 
> That's totally expected and right.
> I just meant wherein the code further motion is prevented. I couldn't find that.

Ah sorry, it is in [Vehicle.clip_actions()](https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L127)

**Comment by mhtb32** [comment]
> Ah sorry, it is in [Vehicle.clip_actions()](https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L127)

Even though `clip_actions()` only checks `self.crashed` and not newly added `self.crashed_with_obstacle()`, yet still, the vehicle is stopped after collision with obstacles. Do you have any idea why?

**Comment by eleurent** [comment]
I had a look. It is because:
1. when crashed_with_obstacle is set to True, the vehicle keeps checking for collisions
2. each time a collision is detected, the speeds of the two objects are set equal to simulate an impact. Thus, the vehicle speed is set to the obstacle speed: 0.

This could be fixed by either adding the condition
```
if self.crashed_with_obstacle
    return
```
or removing the change of speed for obstacles: https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L174

But none of these really make sense: colliding with an obstacle SHOULD stop the vehicle. I guess the required change is implementing the landmark, with a common interface.

**Comment by mhtb32** [comment]
> Ah sorry, it is in [Vehicle.clip_actions()](https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L127)

Finally found it :sweat_smile:
It is actually [this line](https://github.com/eleurent/highway-env/blob/master/highway_env/vehicle/kinematics.py#L174) which stops the vehicle when colliding with an obstacle.

**Comment by mhtb32** [comment]
Yes. it makes the code verbose. I agree that the better solution is to implement Obstacle and Landmark classes.

**Pull request merged**
