### PR TITLE
Common interface for road objects

### PR DESCRIPTION
**Pull request by mhtb32**
This pull request proposes an initial implementation of the feature described in #56 

I should explain a few things:

1. Inheriting empty classes `Obstacle` and `Landmark` may be controversial, since adding just a property to `RoadObject` class might do the benefit I seek. But I did this for the sake of further development in the future.

2. Because `parking-env` used `to_dict()` method of the former `Obstacle` class, I had to implement that in the `RoadObjects`, but it doesn't make sense and I propose changing `parking-env` later on.

3. I've added a test for modified `check_collision()` function in the `test_dynamics.py` file, feel free to edit the location if you think it should be in another file.

Because of the many changes in master, I had to do a breathtaking rebase :sweat_smile: I hope nothing went wrong.

### CODE REVIEW

**Comment by eleurent** [comment]
Good job, thanks!
One remark: I initially thought that all objects -including vehicles- would inherit from the same RoadObject interface, with basic properties: shape, color, position. Instead you have separated vehicles from static objects, which is also fine and will do for the moment :)

**Comment by eleurent** [comment]
Also, sorry about all the rebasing you had to go through, and thanks for the nice touch of adding a test 👍

**Comment by mhtb32** [comment]
> Also, sorry about all the rebasing you had to go through, and thanks for the nice touch of adding a test

Nothing to be sorry for, keep doing great work :muscle:

**Comment by mhtb32** [comment]
> One remark: I initially thought that all objects -including vehicles- would inherit from the same RoadObject interface, with basic properties: shape, color, position. Instead you have separated vehicles from static objects, which is also fine and will do for the moment :)

That's a good idea. I'll add this to #56 issue.

**Pull request merged**
